[package]
name = "greet-user"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
wasmtime = { version = "26.0.0", features = ["runtime"] }
